### ISSUE TITLE
Unable to freeze or heat Litherite

### ISSUE THREAD

**Issue by Aetrnl94** [LightBlueGamer/Lithereal#1]
Hi, I'm having an issue using the fire crucible. Can anyone give guidance on how to create the burning crystals? I've tried moving the coal and Litherite crystals to all 3 possible locations with no luck.

I assume that my interface looks like this because of SOME mod or another (as I'm currently running over 350), but if anyone can show me what it's supposed to look like I'd appreciate it! 🙂

![Screenshot 2023-08-21 103249](https://github.com/LightBlueGamer/Lithereal/assets/131720204/1f4aad0e-8aca-4710-acef-5c86db51b443)
![Screenshot 2023-08-21 103234](https://github.com/LightBlueGamer/Lithereal/assets/131720204/23ac3dbd-bc76-4c57-9aab-8326f3bf4901)
![Screenshot 2023-08-21 103209](https://github.com/LightBlueGamer/Lithereal/assets/131720204/f0a7c33b-2c29-4356-b67e-b647f3b5e781)
![Screenshot 2023-08-21 103351](https://github.com/LightBlueGamer/Lithereal/assets/131720204/d759e18a-3ba3-409f-977c-1d8d19a9a1c9)
![Screenshot 2023-08-21 103339](https://github.com/LightBlueGamer/Lithereal/assets/131720204/1bf8572e-6bc5-4a85-8ced-9e8b934aae17)
![Screenshot 2023-08-21 103325](https://github.com/LightBlueGamer/Lithereal/assets/131720204/d4c2713d-61ed-49d1-bf0a-37a076b24244)
![Screenshot 2023-08-21 103303](https://github.com/LightBlueGamer/Lithereal/assets/131720204/de873f42-30be-48c3-b9fa-df408a41d163)

**Comment by LightBlueGamer** [comment]
Solid fuel source top right, litherite crystal bottom, output at the top. If I'm not wrong whilst updating 1.3 and pushing out updates to github. I must've forgotten to re-jar the files and used old files for uploading 1.3 after testing hence the missing GUI & functionality. I will fix both the GUI and the solid fuel function ASAP, for now using a heat source block beneath the fire crucible will work to fuel it. Valid fuel sources are a heated litherite block, lava or fire. Thanks for letting us know!
