### ISSUE TITLE
Non-instant potion effects create incorrect behavior for infused blocks

### ISSUE THREAD

**Issue by ghost** [LightBlueGamer/Lithereal#7]
Potion effects that are not instant (i.e Poison) do not work correctly as standing on an infused Litherite block applies the effect for one tick every single tick, making the effect useless. In other scenarios like Night Vision, this behavior creates unwanted side effects like flashing or non-optimal implementation. 

This bug can be seen in the [following](https://www.youtube.com/watch?v=Dec9qUZIiCA
) video:

Additionally, uncraftable infused blocks turn into Poison infused blocks on relog, as shown in [this](https://www.youtube.com/watch?v=vQv5taMC2p0) video.

**Comment by ghost** [comment]
The fix currently implemented does not work for non-instant effects, such as Withering which requires several seconds for the effect to work properly.

**Comment by StunfMC** [comment]
While the duration of the Withering effect on the block has been increased in [04d5cfc](https://github.com/LightBlueGamer/Lithereal/commit/04d5cfc7dd8ef1d8788dc87816b3efb616d0915f), this still creates a consistency issue which I believe should be further addressed.
